/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import type { TypedEventFilter, TypedEvent, TypedListener } from './common';

interface ICoverPoolFactoryInterface extends ethers.utils.Interface {
  functions: {
    'coverPools(bytes32)': FunctionFragment;
    'createCoverPool(bytes32,address,address,uint16,int16,uint16)': FunctionFragment;
    'getCoverPool(bytes32,address,address,uint16,int16,uint16)': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'coverPools',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'createCoverPool',
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'getCoverPool',
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
    ],
  ): string;

  decodeFunctionResult(functionFragment: 'coverPools', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'createCoverPool',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getCoverPool',
    data: BytesLike,
  ): Result;

  events: {};
}

export class ICoverPoolFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICoverPoolFactoryInterface;

  functions: {
    coverPools(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    createCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    getCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string] & { pool: string }>;
  };

  coverPools(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  createCoverPool(
    sourceName: BytesLike,
    tokenIn: string,
    tokenOut: string,
    fee: BigNumberish,
    tickSpread: BigNumberish,
    twapLength: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  getCoverPool(
    sourceName: BytesLike,
    tokenIn: string,
    tokenOut: string,
    fee: BigNumberish,
    tickSpread: BigNumberish,
    twapLength: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    coverPools(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    createCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    getCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    coverPools(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    createCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    getCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    coverPools(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    createCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    getCoverPool(
      sourceName: BytesLike,
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      tickSpread: BigNumberish,
      twapLength: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
