/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import type { TypedEventFilter, TypedEvent, TypedListener } from './common';

interface RangePoolFactoryMockInterface extends ethers.utils.Interface {
  functions: {
    'feeTierTickSpacing(uint24)': FunctionFragment;
    'getRangePool(address,address,uint16)': FunctionFragment;
    'rangePools(address,address,uint24)': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'feeTierTickSpacing',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'getRangePool',
    values: [string, string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'rangePools',
    values: [string, string, BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'feeTierTickSpacing',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getRangePool',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'rangePools', data: BytesLike): Result;

  events: {};
}

export class RangePoolFactoryMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RangePoolFactoryMockInterface;

  functions: {
    feeTierTickSpacing(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[number]>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      feeTier: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    rangePools(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;
  };

  feeTierTickSpacing(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<number>;

  getRangePool(
    tokenIn: string,
    tokenOut: string,
    feeTier: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  rangePools(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    feeTierTickSpacing(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<number>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      feeTier: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    rangePools(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    feeTierTickSpacing(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      feeTier: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    rangePools(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    feeTierTickSpacing(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      feeTier: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    rangePools(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
