/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RangePoolFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createRangePool(address,address,uint16,uint160)": FunctionFragment;
    "getRangePool(address,address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "rangePools(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createRangePool",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRangePool",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rangePools",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createRangePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRangePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rangePools", data: BytesLike): Result;

  events: {
    "RangePoolCreated(address,address,uint24,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RangePoolCreated"): EventFragment;
}

export type RangePoolCreatedEvent = TypedEvent<
  [string, string, number, string] & {
    token0: string;
    token1: string;
    fee: number;
    pool: string;
  }
>;

export class RangePoolFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RangePoolFactoryInterface;

  functions: {
    createRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      startPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rangePools(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;
  };

  createRangePool(
    tokenIn: string,
    tokenOut: string,
    swapFee: BigNumberish,
    startPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getRangePool(
    tokenIn: string,
    tokenOut: string,
    swapFee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  rangePools(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      startPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    rangePools(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "RangePoolCreated(address,address,uint24,address)"(
      token0?: string | null,
      token1?: string | null,
      fee?: BigNumberish | null,
      pool?: null
    ): TypedEventFilter<
      [string, string, number, string],
      { token0: string; token1: string; fee: number; pool: string }
    >;

    RangePoolCreated(
      token0?: string | null,
      token1?: string | null,
      fee?: BigNumberish | null,
      pool?: null
    ): TypedEventFilter<
      [string, string, number, string],
      { token0: string; token1: string; fee: number; pool: string }
    >;
  };

  estimateGas: {
    createRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      startPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rangePools(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      startPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getRangePool(
      tokenIn: string,
      tokenOut: string,
      swapFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rangePools(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
