/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CoverPoolInterface extends ethers.utils.Interface {
  functions: {
    "auctionLength()": FunctionFragment;
    "blockTime()": FunctionFragment;
    "burn((address,uint128,int24,int24,int24,bool,bool))": FunctionFragment;
    "feeTo()": FunctionFragment;
    "fees(uint16,uint16,bool)": FunctionFragment;
    "genesisTime()": FunctionFragment;
    "globalState()": FunctionFragment;
    "inputPool()": FunctionFragment;
    "maxPrice()": FunctionFragment;
    "minAmountLowerPriced()": FunctionFragment;
    "minAmountPerAuction()": FunctionFragment;
    "minPositionWidth()": FunctionFragment;
    "minPrice()": FunctionFragment;
    "mint((address,uint128,int24,int24,bool))": FunctionFragment;
    "owner()": FunctionFragment;
    "pool0()": FunctionFragment;
    "pool1()": FunctionFragment;
    "positions0(address,int24,int24)": FunctionFragment;
    "positions1(address,int24,int24)": FunctionFragment;
    "quote((uint160,uint128,bool))": FunctionFragment;
    "snapshot((address,uint128,int24,int24,int24,bool))": FunctionFragment;
    "swap((address,address,uint160,uint128,bool))": FunctionFragment;
    "tickMap()": FunctionFragment;
    "tickSpread()": FunctionFragment;
    "ticks0(int24)": FunctionFragment;
    "ticks1(int24)": FunctionFragment;
    "token0()": FunctionFragment;
    "token1()": FunctionFragment;
    "twapLength()": FunctionFragment;
    "twapSource()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "auctionLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "blockTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [
      {
        to: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
        sync: boolean;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "feeTo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fees",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalState",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "inputPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minAmountLowerPriced",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minAmountPerAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPositionWidth",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [
      {
        to: string;
        amount: BigNumberish;
        lower: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool0", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions0",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "positions1",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [
      { priceLimit: BigNumberish; amountIn: BigNumberish; zeroForOne: boolean }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshot",
    values: [
      {
        owner: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      {
        to: string;
        refundTo: string;
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "tickMap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tickSpread",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticks0",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticks1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "twapLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "twapSource",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blockTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genesisTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inputPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minAmountLowerPriced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minAmountPerAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPositionWidth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tickMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tickSpread", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ticks0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ticks1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "twapLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "twapSource", data: BytesLike): Result;

  events: {};
}

export class CoverPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CoverPoolInterface;

  functions: {
    auctionLength(overrides?: CallOverrides): Promise<[number]>;

    blockTime(overrides?: CallOverrides): Promise<[number]>;

    burn(
      params: {
        to: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
        sync: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    feeTo(overrides?: CallOverrides): Promise<[string]>;

    fees(
      syncFee: BigNumberish,
      fillFee: BigNumberish,
      setFees: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    genesisTime(overrides?: CallOverrides): Promise<[number]>;

    globalState(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & { token0: BigNumber; token1: BigNumber },
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ] & {
        protocolFees: [BigNumber, BigNumber] & {
          token0: BigNumber;
          token1: BigNumber;
        };
        latestPrice: BigNumber;
        liquidityGlobal: BigNumber;
        lastTime: number;
        auctionStart: number;
        accumEpoch: number;
        latestTick: number;
        syncFee: number;
        fillFee: number;
        unlocked: number;
      }
    >;

    inputPool(overrides?: CallOverrides): Promise<[string]>;

    maxPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    minAmountLowerPriced(overrides?: CallOverrides): Promise<[boolean]>;

    minAmountPerAuction(overrides?: CallOverrides): Promise<[BigNumber]>;

    minPositionWidth(overrides?: CallOverrides): Promise<[number]>;

    minPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      params: {
        to: string;
        amount: BigNumberish;
        lower: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pool0(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        price: BigNumber;
        liquidity: BigNumber;
        amountInDelta: BigNumber;
        amountInDeltaMaxClaimed: BigNumber;
        amountOutDeltaMaxClaimed: BigNumber;
      }
    >;

    pool1(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        price: BigNumber;
        liquidity: BigNumber;
        amountInDelta: BigNumber;
        amountInDeltaMaxClaimed: BigNumber;
        amountOutDeltaMaxClaimed: BigNumber;
      }
    >;

    positions0(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        claimPriceLast: BigNumber;
        liquidity: BigNumber;
        amountIn: BigNumber;
        amountOut: BigNumber;
        accumEpochLast: number;
      }
    >;

    positions1(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        claimPriceLast: BigNumber;
        liquidity: BigNumber;
        amountIn: BigNumber;
        amountOut: BigNumber;
        accumEpochLast: number;
      }
    >;

    quote(
      params: {
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        inAmount: BigNumber;
        outAmount: BigNumber;
        priceAfter: BigNumber;
      }
    >;

    snapshot(
      params: {
        owner: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
          claimPriceLast: BigNumber;
          liquidity: BigNumber;
          amountIn: BigNumber;
          amountOut: BigNumber;
          accumEpochLast: number;
        }
      ]
    >;

    swap(
      params: {
        to: string;
        refundTo: string;
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tickMap(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { blocks: BigNumber }>;

    tickSpread(overrides?: CallOverrides): Promise<[number]>;

    ticks0(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        },
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        };
        liquidityDelta: BigNumber;
        amountInDeltaMaxMinus: BigNumber;
        amountOutDeltaMaxMinus: BigNumber;
        amountInDeltaMaxStashed: BigNumber;
        amountOutDeltaMaxStashed: BigNumber;
      }
    >;

    ticks1(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        },
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        };
        liquidityDelta: BigNumber;
        amountInDeltaMaxMinus: BigNumber;
        amountOutDeltaMaxMinus: BigNumber;
        amountInDeltaMaxStashed: BigNumber;
        amountOutDeltaMaxStashed: BigNumber;
      }
    >;

    token0(overrides?: CallOverrides): Promise<[string]>;

    token1(overrides?: CallOverrides): Promise<[string]>;

    twapLength(overrides?: CallOverrides): Promise<[number]>;

    twapSource(overrides?: CallOverrides): Promise<[string]>;
  };

  auctionLength(overrides?: CallOverrides): Promise<number>;

  blockTime(overrides?: CallOverrides): Promise<number>;

  burn(
    params: {
      to: string;
      burnPercent: BigNumberish;
      lower: BigNumberish;
      claim: BigNumberish;
      upper: BigNumberish;
      zeroForOne: boolean;
      sync: boolean;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  feeTo(overrides?: CallOverrides): Promise<string>;

  fees(
    syncFee: BigNumberish,
    fillFee: BigNumberish,
    setFees: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  genesisTime(overrides?: CallOverrides): Promise<number>;

  globalState(
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, BigNumber] & { token0: BigNumber; token1: BigNumber },
      BigNumber,
      BigNumber,
      number,
      number,
      number,
      number,
      number,
      number,
      number
    ] & {
      protocolFees: [BigNumber, BigNumber] & {
        token0: BigNumber;
        token1: BigNumber;
      };
      latestPrice: BigNumber;
      liquidityGlobal: BigNumber;
      lastTime: number;
      auctionStart: number;
      accumEpoch: number;
      latestTick: number;
      syncFee: number;
      fillFee: number;
      unlocked: number;
    }
  >;

  inputPool(overrides?: CallOverrides): Promise<string>;

  maxPrice(overrides?: CallOverrides): Promise<BigNumber>;

  minAmountLowerPriced(overrides?: CallOverrides): Promise<boolean>;

  minAmountPerAuction(overrides?: CallOverrides): Promise<BigNumber>;

  minPositionWidth(overrides?: CallOverrides): Promise<number>;

  minPrice(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    params: {
      to: string;
      amount: BigNumberish;
      lower: BigNumberish;
      upper: BigNumberish;
      zeroForOne: boolean;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pool0(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      price: BigNumber;
      liquidity: BigNumber;
      amountInDelta: BigNumber;
      amountInDeltaMaxClaimed: BigNumber;
      amountOutDeltaMaxClaimed: BigNumber;
    }
  >;

  pool1(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      price: BigNumber;
      liquidity: BigNumber;
      amountInDelta: BigNumber;
      amountInDeltaMaxClaimed: BigNumber;
      amountOutDeltaMaxClaimed: BigNumber;
    }
  >;

  positions0(
    arg0: string,
    arg1: BigNumberish,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      claimPriceLast: BigNumber;
      liquidity: BigNumber;
      amountIn: BigNumber;
      amountOut: BigNumber;
      accumEpochLast: number;
    }
  >;

  positions1(
    arg0: string,
    arg1: BigNumberish,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      claimPriceLast: BigNumber;
      liquidity: BigNumber;
      amountIn: BigNumber;
      amountOut: BigNumber;
      accumEpochLast: number;
    }
  >;

  quote(
    params: {
      priceLimit: BigNumberish;
      amountIn: BigNumberish;
      zeroForOne: boolean;
    },
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      inAmount: BigNumber;
      outAmount: BigNumber;
      priceAfter: BigNumber;
    }
  >;

  snapshot(
    params: {
      owner: string;
      burnPercent: BigNumberish;
      lower: BigNumberish;
      claim: BigNumberish;
      upper: BigNumberish;
      zeroForOne: boolean;
    },
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
      claimPriceLast: BigNumber;
      liquidity: BigNumber;
      amountIn: BigNumber;
      amountOut: BigNumber;
      accumEpochLast: number;
    }
  >;

  swap(
    params: {
      to: string;
      refundTo: string;
      priceLimit: BigNumberish;
      amountIn: BigNumberish;
      zeroForOne: boolean;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tickMap(overrides?: CallOverrides): Promise<BigNumber>;

  tickSpread(overrides?: CallOverrides): Promise<number>;

  ticks0(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountInDelta: BigNumber;
        amountOutDelta: BigNumber;
        amountInDeltaMax: BigNumber;
        amountOutDeltaMax: BigNumber;
      },
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountInDelta: BigNumber;
        amountOutDelta: BigNumber;
        amountInDeltaMax: BigNumber;
        amountOutDeltaMax: BigNumber;
      };
      liquidityDelta: BigNumber;
      amountInDeltaMaxMinus: BigNumber;
      amountOutDeltaMaxMinus: BigNumber;
      amountInDeltaMaxStashed: BigNumber;
      amountOutDeltaMaxStashed: BigNumber;
    }
  >;

  ticks1(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountInDelta: BigNumber;
        amountOutDelta: BigNumber;
        amountInDeltaMax: BigNumber;
        amountOutDeltaMax: BigNumber;
      },
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amountInDelta: BigNumber;
        amountOutDelta: BigNumber;
        amountInDeltaMax: BigNumber;
        amountOutDeltaMax: BigNumber;
      };
      liquidityDelta: BigNumber;
      amountInDeltaMaxMinus: BigNumber;
      amountOutDeltaMaxMinus: BigNumber;
      amountInDeltaMaxStashed: BigNumber;
      amountOutDeltaMaxStashed: BigNumber;
    }
  >;

  token0(overrides?: CallOverrides): Promise<string>;

  token1(overrides?: CallOverrides): Promise<string>;

  twapLength(overrides?: CallOverrides): Promise<number>;

  twapSource(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    auctionLength(overrides?: CallOverrides): Promise<number>;

    blockTime(overrides?: CallOverrides): Promise<number>;

    burn(
      params: {
        to: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
        sync: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    feeTo(overrides?: CallOverrides): Promise<string>;

    fees(
      syncFee: BigNumberish,
      fillFee: BigNumberish,
      setFees: boolean,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { token0Fees: BigNumber; token1Fees: BigNumber }
    >;

    genesisTime(overrides?: CallOverrides): Promise<number>;

    globalState(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & { token0: BigNumber; token1: BigNumber },
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ] & {
        protocolFees: [BigNumber, BigNumber] & {
          token0: BigNumber;
          token1: BigNumber;
        };
        latestPrice: BigNumber;
        liquidityGlobal: BigNumber;
        lastTime: number;
        auctionStart: number;
        accumEpoch: number;
        latestTick: number;
        syncFee: number;
        fillFee: number;
        unlocked: number;
      }
    >;

    inputPool(overrides?: CallOverrides): Promise<string>;

    maxPrice(overrides?: CallOverrides): Promise<BigNumber>;

    minAmountLowerPriced(overrides?: CallOverrides): Promise<boolean>;

    minAmountPerAuction(overrides?: CallOverrides): Promise<BigNumber>;

    minPositionWidth(overrides?: CallOverrides): Promise<number>;

    minPrice(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      params: {
        to: string;
        amount: BigNumberish;
        lower: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pool0(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        price: BigNumber;
        liquidity: BigNumber;
        amountInDelta: BigNumber;
        amountInDeltaMaxClaimed: BigNumber;
        amountOutDeltaMaxClaimed: BigNumber;
      }
    >;

    pool1(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        price: BigNumber;
        liquidity: BigNumber;
        amountInDelta: BigNumber;
        amountInDeltaMaxClaimed: BigNumber;
        amountOutDeltaMaxClaimed: BigNumber;
      }
    >;

    positions0(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        claimPriceLast: BigNumber;
        liquidity: BigNumber;
        amountIn: BigNumber;
        amountOut: BigNumber;
        accumEpochLast: number;
      }
    >;

    positions1(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        claimPriceLast: BigNumber;
        liquidity: BigNumber;
        amountIn: BigNumber;
        amountOut: BigNumber;
        accumEpochLast: number;
      }
    >;

    quote(
      params: {
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        inAmount: BigNumber;
        outAmount: BigNumber;
        priceAfter: BigNumber;
      }
    >;

    snapshot(
      params: {
        owner: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, number] & {
        claimPriceLast: BigNumber;
        liquidity: BigNumber;
        amountIn: BigNumber;
        amountOut: BigNumber;
        accumEpochLast: number;
      }
    >;

    swap(
      params: {
        to: string;
        refundTo: string;
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        inAmount: BigNumber;
        outAmount: BigNumber;
        priceAfter: BigNumber;
      }
    >;

    tickMap(overrides?: CallOverrides): Promise<BigNumber>;

    tickSpread(overrides?: CallOverrides): Promise<number>;

    ticks0(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        },
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        };
        liquidityDelta: BigNumber;
        amountInDeltaMaxMinus: BigNumber;
        amountOutDeltaMaxMinus: BigNumber;
        amountInDeltaMaxStashed: BigNumber;
        amountOutDeltaMaxStashed: BigNumber;
      }
    >;

    ticks1(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        },
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        deltas: [BigNumber, BigNumber, BigNumber, BigNumber] & {
          amountInDelta: BigNumber;
          amountOutDelta: BigNumber;
          amountInDeltaMax: BigNumber;
          amountOutDeltaMax: BigNumber;
        };
        liquidityDelta: BigNumber;
        amountInDeltaMaxMinus: BigNumber;
        amountOutDeltaMaxMinus: BigNumber;
        amountInDeltaMaxStashed: BigNumber;
        amountOutDeltaMaxStashed: BigNumber;
      }
    >;

    token0(overrides?: CallOverrides): Promise<string>;

    token1(overrides?: CallOverrides): Promise<string>;

    twapLength(overrides?: CallOverrides): Promise<number>;

    twapSource(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    auctionLength(overrides?: CallOverrides): Promise<BigNumber>;

    blockTime(overrides?: CallOverrides): Promise<BigNumber>;

    burn(
      params: {
        to: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
        sync: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    feeTo(overrides?: CallOverrides): Promise<BigNumber>;

    fees(
      syncFee: BigNumberish,
      fillFee: BigNumberish,
      setFees: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    genesisTime(overrides?: CallOverrides): Promise<BigNumber>;

    globalState(overrides?: CallOverrides): Promise<BigNumber>;

    inputPool(overrides?: CallOverrides): Promise<BigNumber>;

    maxPrice(overrides?: CallOverrides): Promise<BigNumber>;

    minAmountLowerPriced(overrides?: CallOverrides): Promise<BigNumber>;

    minAmountPerAuction(overrides?: CallOverrides): Promise<BigNumber>;

    minPositionWidth(overrides?: CallOverrides): Promise<BigNumber>;

    minPrice(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      params: {
        to: string;
        amount: BigNumberish;
        lower: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pool0(overrides?: CallOverrides): Promise<BigNumber>;

    pool1(overrides?: CallOverrides): Promise<BigNumber>;

    positions0(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    positions1(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quote(
      params: {
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    snapshot(
      params: {
        owner: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swap(
      params: {
        to: string;
        refundTo: string;
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tickMap(overrides?: CallOverrides): Promise<BigNumber>;

    tickSpread(overrides?: CallOverrides): Promise<BigNumber>;

    ticks0(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    ticks1(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    token0(overrides?: CallOverrides): Promise<BigNumber>;

    token1(overrides?: CallOverrides): Promise<BigNumber>;

    twapLength(overrides?: CallOverrides): Promise<BigNumber>;

    twapSource(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blockTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burn(
      params: {
        to: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
        sync: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    feeTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fees(
      syncFee: BigNumberish,
      fillFee: BigNumberish,
      setFees: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    genesisTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    globalState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    inputPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minAmountLowerPriced(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minAmountPerAuction(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minPositionWidth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      params: {
        to: string;
        amount: BigNumberish;
        lower: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positions0(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positions1(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quote(
      params: {
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    snapshot(
      params: {
        owner: string;
        burnPercent: BigNumberish;
        lower: BigNumberish;
        claim: BigNumberish;
        upper: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swap(
      params: {
        to: string;
        refundTo: string;
        priceLimit: BigNumberish;
        amountIn: BigNumberish;
        zeroForOne: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tickMap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tickSpread(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ticks0(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ticks1(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    twapLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    twapSource(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
