/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CoverPoolFactoryStorage,
  CoverPoolFactoryStorageInterface,
} from "../CoverPoolFactoryStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "coverPools",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CoverPoolFactoryStorage__factory {
  static readonly abi = _abi;
  static createInterface(): CoverPoolFactoryStorageInterface {
    return new utils.Interface(_abi) as CoverPoolFactoryStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoverPoolFactoryStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CoverPoolFactoryStorage;
  }
}
