/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type {
  RangePoolFactoryStorage,
  RangePoolFactoryStorageInterface,
} from '../RangePoolFactoryStorage';

const _abi = [
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'rangePools',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class RangePoolFactoryStorage__factory {
  static readonly abi = _abi;
  static createInterface(): RangePoolFactoryStorageInterface {
    return new utils.Interface(_abi) as RangePoolFactoryStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): RangePoolFactoryStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider,
    ) as RangePoolFactoryStorage;
  }
}
