/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  RangePoolManagerEvents,
  RangePoolManagerEventsInterface,
} from "../RangePoolManagerEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousFactory",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newFactory",
        type: "address",
      },
    ],
    name: "FactoryChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint16",
        name: "swapFee",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
    ],
    name: "FeeTierEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousFeeTo",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newFeeTo",
        type: "address",
      },
    ],
    name: "FeeToTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnerTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address[]",
        name: "pool",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint128[]",
        name: "token0Fees",
        type: "uint128[]",
      },
      {
        indexed: false,
        internalType: "uint128[]",
        name: "token1Fees",
        type: "uint128[]",
      },
    ],
    name: "ProtocolFeeCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address[]",
        name: "pool",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "protocolFee",
        type: "uint16",
      },
    ],
    name: "ProtocolFeeUpdated",
    type: "event",
  },
];

export class RangePoolManagerEvents__factory {
  static readonly abi = _abi;
  static createInterface(): RangePoolManagerEventsInterface {
    return new utils.Interface(_abi) as RangePoolManagerEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RangePoolManagerEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RangePoolManagerEvents;
  }
}
